changes = {
    65476: {'changes': {'solo': True},
         'post': {'approver_id': 2080,
                  'change_seq': 33992586,
                  'comment_count': 11,
                  'created_at': '2010-03-23T13:14:24.017-04:00',
                  'description': '',
                  'duration': None,
                  'fav_count': 99,
                  'file': {'ext': 'jpg',
                           'height': 1280,
                           'md5': '662cb82ee619d0a166f32da4773d9ac1',
                           'size': 483394,
                           'url': 'https://static1.e621.net/data/66/2c/662cb82ee619d0a166f32da4773d9ac1.jpg',
                           'width': 1920},
                  'flags': {'deleted': False,
                            'flagged': False,
                            'note_locked': False,
                            'pending': False,
                            'rating_locked': False,
                            'status_locked': False},
                  'has_notes': False,
                  'id': 65476,
                  'is_favorited': False,
                  'locked_tags': [],
                  'pools': [],
                  'preview': {'height': 100,
                              'url': 'https://static1.e621.net/data/preview/66/2c/662cb82ee619d0a166f32da4773d9ac1.jpg',
                              'width': 150},
                  'rating': 's',
                  'relationships': {'children': [],
                                    'has_active_children': False,
                                    'has_children': False,
                                    'parent_id': None},
                  'sample': {'alternates': {},
                             'has': True,
                             'height': 566,
                             'url': 'https://static1.e621.net/data/sample/66/2c/662cb82ee619d0a166f32da4773d9ac1.jpg',
                             'width': 850},
                  'score': {'down': -1, 'total': 30, 'up': 30},
                  'sources': ['https://danbooru.donmai.us/data/662cb82ee619d0a166f32da4773d9ac1.jpg'],
                  'tags': {'artist': ['mri'],
                           'character': ['shadow_the_hedgehog'],
                           'copyright': ['sega', 'sonic_the_hedgehog_(series)'],
                           'general': ['anthro',
                                       'black_body',
                                       'black_fur',
                                       'chaos_control',
                                       'chaos_emerald',
                                       'clothing',
                                       'footwear',
                                       'fur',
                                       'gloves',
                                       'handwear',
                                       'looking_at_viewer',
                                       'looking_back',
                                       'male',
                                       'red_body',
                                       'red_eyes',
                                       'red_fur',
                                       'shoes',
                                       'tan_body',
                                       'tan_skin'],
                           'invalid': [],
                           'lore': [],
                           'meta': ['3:2', 'hi_res', 'wallpaper', 'widescreen'],
                           'species': ['eulipotyphlan', 'hedgehog', 'mammal']},
                  'updated_at': '2021-07-05T20:56:18.694-04:00',
                  'uploader_id': 1159}},
 109787: {'changes': {'set:conman_test': True},
          'post': {'approver_id': None,
                   'change_seq': 21663327,
                   'comment_count': 1,
                   'created_at': '2011-01-01T00:28:56.671-05:00',
                   'description': '',
                   'duration': None,
                   'fav_count': 3,
                   'file': {'ext': 'jpg',
                            'height': 1029,
                            'md5': '03dcf3aaa34bcbdce81d2eac1d83a97d',
                            'size': 358755,
                            'url': 'https://static1.e621.net/data/03/dc/03dcf3aaa34bcbdce81d2eac1d83a97d.jpg',
                            'width': 800},
                   'flags': {'deleted': False,
                             'flagged': False,
                             'note_locked': False,
                             'pending': False,
                             'rating_locked': False,
                             'status_locked': False},
                   'has_notes': False,
                   'id': 109787,
                   'is_favorited': False,
                   'locked_tags': [],
                   'pools': [603],
                   'preview': {'height': 150,
                               'url': 'https://static1.e621.net/data/preview/03/dc/03dcf3aaa34bcbdce81d2eac1d83a97d.jpg',
                               'width': 116},
                   'rating': 's',
                   'relationships': {'children': [],
                                     'has_active_children': False,
                                     'has_children': False,
                                     'parent_id': None},
                   'sample': {'alternates': {},
                              'has': False,
                              'height': 1029,
                              'url': 'https://static1.e621.net/data/03/dc/03dcf3aaa34bcbdce81d2eac1d83a97d.jpg',
                              'width': 800},
                   'score': {'down': 0, 'total': 2, 'up': 2},
                   'sources': ['Image board'],
                   'tags': {'artist': ['fruitz'],
                            'character': [],
                            'copyright': [],
                            'general': ['anthro',
                                        'computer',
                                        'dialogue',
                                        'laptop',
                                        'male',
                                        'phone',
                                        'text'],
                            'invalid': [],
                            'lore': [],
                            'meta': ['comic',
                                     'edit',
                                     'english_text',
                                     'greyscale',
                                     'hard_translated',
                                     'monochrome',
                                     'translated'],
                            'species': ['canid',
                                        'canine',
                                        'canis',
                                        'domestic_dog',
                                        'felid',
                                        'mammal',
                                        'pantherine',
                                        'tiger']},
                   'updated_at': None,
                   'uploader_id': 12705}},
 109788: {'changes': {'set:conman_test': True},
          'post': {'approver_id': None,
                   'change_seq': 21663329,
                   'comment_count': 0,
                   'created_at': '2011-01-01T00:29:04.124-05:00',
                   'description': '',
                   'duration': None,
                   'fav_count': 2,
                   'file': {'ext': 'jpg',
                            'height': 1032,
                            'md5': '1157d64070aefa32573707591637c105',
                            'size': 361729,
                            'url': 'https://static1.e621.net/data/11/57/1157d64070aefa32573707591637c105.jpg',
                            'width': 800},
                   'flags': {'deleted': False,
                             'flagged': False,
                             'note_locked': False,
                             'pending': False,
                             'rating_locked': False,
                             'status_locked': False},
                   'has_notes': False,
                   'id': 109788,
                   'is_favorited': False,
                   'locked_tags': [],
                   'pools': [603],
                   'preview': {'height': 150,
                               'url': 'https://static1.e621.net/data/preview/11/57/1157d64070aefa32573707591637c105.jpg',
                               'width': 116},
                   'rating': 's',
                   'relationships': {'children': [],
                                     'has_active_children': False,
                                     'has_children': False,
                                     'parent_id': None},
                   'sample': {'alternates': {},
                              'has': False,
                              'height': 1032,
                              'url': 'https://static1.e621.net/data/11/57/1157d64070aefa32573707591637c105.jpg',
                              'width': 800},
                   'score': {'down': 0, 'total': 2, 'up': 2},
                   'sources': ['Image board'],
                   'tags': {'artist': ['fruitz'],
                            'character': [],
                            'copyright': [],
                            'general': ['anthro',
                                        'computer',
                                        'dialogue',
                                        'laptop',
                                        'male',
                                        'text'],
                            'invalid': [],
                            'lore': [],
                            'meta': ['comic',
                                     'edit',
                                     'english_text',
                                     'greyscale',
                                     'hard_translated',
                                     'monochrome',
                                     'translated'],
                            'species': ['canid',
                                        'canine',
                                        'canis',
                                        'domestic_dog',
                                        'felid',
                                        'mammal',
                                        'pantherine',
                                        'tiger']},
                   'updated_at': None,
                   'uploader_id': 12705}},
 109789: {'changes': {'set:conman_test': True},
          'post': {'approver_id': None,
                   'change_seq': 31749164,
                   'comment_count': 0,
                   'created_at': '2011-01-01T00:29:11.567-05:00',
                   'description': '',
                   'duration': None,
                   'fav_count': 2,
                   'file': {'ext': 'jpg',
                            'height': 1026,
                            'md5': '4e6cf4dda2d069c9b69875dabb79479f',
                            'size': 338998,
                            'url': 'https://static1.e621.net/data/4e/6c/4e6cf4dda2d069c9b69875dabb79479f.jpg',
                            'width': 800},
                   'flags': {'deleted': False,
                             'flagged': False,
                             'note_locked': False,
                             'pending': False,
                             'rating_locked': False,
                             'status_locked': False},
                   'has_notes': False,
                   'id': 109789,
                   'is_favorited': False,
                   'locked_tags': [],
                   'pools': [603],
                   'preview': {'height': 150,
                               'url': 'https://static1.e621.net/data/preview/4e/6c/4e6cf4dda2d069c9b69875dabb79479f.jpg',
                               'width': 116},
                   'rating': 's',
                   'relationships': {'children': [],
                                     'has_active_children': False,
                                     'has_children': False,
                                     'parent_id': None},
                   'sample': {'alternates': {},
                              'has': False,
                              'height': 1026,
                              'url': 'https://static1.e621.net/data/4e/6c/4e6cf4dda2d069c9b69875dabb79479f.jpg',
                              'width': 800},
                   'score': {'down': 0, 'total': 2, 'up': 2},
                   'sources': ['Image board'],
                   'tags': {'artist': ['fruitz'],
                            'character': [],
                            'copyright': [],
                            'general': ['anthro',
                                        'dialogue',
                                        'female',
                                        'male',
                                        'text'],
                            'invalid': [],
                            'lore': [],
                            'meta': ['comic',
                                     'edit',
                                     'english_text',
                                     'greyscale',
                                     'hard_translated',
                                     'monochrome',
                                     'translated'],
                            'species': ['canid',
                                        'canine',
                                        'canis',
                                        'domestic_dog',
                                        'felid',
                                        'mammal',
                                        'pantherine',
                                        'tiger']},
                   'updated_at': '2021-01-30T12:13:48.061-05:00',
                   'uploader_id': 12705}},
 109790: {'changes': {'duo': True},
          'post': {'approver_id': None,
                   'change_seq': 21663330,
                   'comment_count': 0,
                   'created_at': '2011-01-01T00:29:19.046-05:00',
                   'description': '',
                   'duration': None,
                   'fav_count': 5,
                   'file': {'ext': 'jpg',
                            'height': 1030,
                            'md5': '0b9d39f850ae364c8a927c48107439ec',
                            'size': 475807,
                            'url': 'https://static1.e621.net/data/0b/9d/0b9d39f850ae364c8a927c48107439ec.jpg',
                            'width': 800},
                   'flags': {'deleted': False,
                             'flagged': False,
                             'note_locked': False,
                             'pending': False,
                             'rating_locked': False,
                             'status_locked': False},
                   'has_notes': False,
                   'id': 109790,
                   'is_favorited': False,
                   'locked_tags': [],
                   'pools': [603],
                   'preview': {'height': 150,
                               'url': 'https://static1.e621.net/data/preview/0b/9d/0b9d39f850ae364c8a927c48107439ec.jpg',
                               'width': 116},
                   'rating': 's',
                   'relationships': {'children': [],
                                     'has_active_children': False,
                                     'has_children': False,
                                     'parent_id': None},
                   'sample': {'alternates': {},
                              'has': False,
                              'height': 1030,
                              'url': 'https://static1.e621.net/data/0b/9d/0b9d39f850ae364c8a927c48107439ec.jpg',
                              'width': 800},
                   'score': {'down': 0, 'total': 1, 'up': 1},
                   'sources': ['Image board'],
                   'tags': {'artist': ['fruitz'],
                            'character': [],
                            'copyright': [],
                            'general': ['anthro', 'dialogue', 'male', 'text'],
                            'invalid': [],
                            'lore': [],
                            'meta': ['comic',
                                     'edit',
                                     'english_text',
                                     'greyscale',
                                     'hard_translated',
                                     'monochrome',
                                     'translated'],
                            'species': ['canid',
                                        'canine',
                                        'canis',
                                        'domestic_dog',
                                        'felid',
                                        'mammal',
                                        'pantherine',
                                        'tiger']},
                   'updated_at': None,
                   'uploader_id': 12705}},
 109791: {'changes': {'duo': True},
          'post': {'approver_id': None,
                   'change_seq': 31749161,
                   'comment_count': 0,
                   'created_at': '2011-01-01T00:29:27.509-05:00',
                   'description': '',
                   'duration': None,
                   'fav_count': 2,
                   'file': {'ext': 'jpg',
                            'height': 1021,
                            'md5': 'b59fdada9c0c71e44edc61489bd857e6',
                            'size': 404300,
                            'url': 'https://static1.e621.net/data/b5/9f/b59fdada9c0c71e44edc61489bd857e6.jpg',
                            'width': 800},
                   'flags': {'deleted': False,
                             'flagged': False,
                             'note_locked': False,
                             'pending': False,
                             'rating_locked': False,
                             'status_locked': False},
                   'has_notes': False,
                   'id': 109791,
                   'is_favorited': False,
                   'locked_tags': [],
                   'pools': [603],
                   'preview': {'height': 150,
                               'url': 'https://static1.e621.net/data/preview/b5/9f/b59fdada9c0c71e44edc61489bd857e6.jpg',
                               'width': 117},
                   'rating': 's',
                   'relationships': {'children': [],
                                     'has_active_children': False,
                                     'has_children': False,
                                     'parent_id': None},
                   'sample': {'alternates': {},
                              'has': False,
                              'height': 1021,
                              'url': 'https://static1.e621.net/data/b5/9f/b59fdada9c0c71e44edc61489bd857e6.jpg',
                              'width': 800},
                   'score': {'down': 0, 'total': 2, 'up': 2},
                   'sources': ['Image board'],
                   'tags': {'artist': ['fruitz'],
                            'character': [],
                            'copyright': [],
                            'general': ['anthro',
                                        'black_bars',
                                        'dialogue',
                                        'letter',
                                        'letterbox',
                                        'male',
                                        'text'],
                            'invalid': [],
                            'lore': [],
                            'meta': ['comic',
                                     'edit',
                                     'english_text',
                                     'greyscale',
                                     'hard_translated',
                                     'monochrome',
                                     'translated'],
                            'species': ['canid',
                                        'canine',
                                        'canis',
                                        'domestic_dog',
                                        'felid',
                                        'mammal',
                                        'pantherine',
                                        'tiger']},
                   'updated_at': '2021-01-30T12:13:25.205-05:00',
                   'uploader_id': 12705}},
 109792: {'changes': {'duo': True},
          'post': {'approver_id': None,
                   'change_seq': 31749158,
                   'comment_count': 0,
                   'created_at': '2011-01-01T00:29:36.122-05:00',
                   'description': '',
                   'duration': None,
                   'fav_count': 5,
                   'file': {'ext': 'jpg',
                            'height': 1042,
                            'md5': 'e9bd2b99719a88a684b90b2bfe08d567',
                            'size': 401079,
                            'url': 'https://static1.e621.net/data/e9/bd/e9bd2b99719a88a684b90b2bfe08d567.jpg',
                            'width': 800},
                   'flags': {'deleted': False,
                             'flagged': False,
                             'note_locked': False,
                             'pending': False,
                             'rating_locked': False,
                             'status_locked': False},
                   'has_notes': False,
                   'id': 109792,
                   'is_favorited': False,
                   'locked_tags': [],
                   'pools': [603],
                   'preview': {'height': 150,
                               'url': 'https://static1.e621.net/data/preview/e9/bd/e9bd2b99719a88a684b90b2bfe08d567.jpg',
                               'width': 115},
                   'rating': 's',
                   'relationships': {'children': [],
                                     'has_active_children': False,
                                     'has_children': False,
                                     'parent_id': None},
                   'sample': {'alternates': {},
                              'has': False,
                              'height': 1042,
                              'url': 'https://static1.e621.net/data/e9/bd/e9bd2b99719a88a684b90b2bfe08d567.jpg',
                              'width': 800},
                   'score': {'down': 0, 'total': 2, 'up': 2},
                   'sources': ['Image board'],
                   'tags': {'artist': ['fruitz'],
                            'character': [],
                            'copyright': [],
                            'general': ['anthro',
                                        'black_bars',
                                        'dialogue',
                                        'letter',
                                        'letterbox',
                                        'male',
                                        'text'],
                            'invalid': [],
                            'lore': [],
                            'meta': ['comic',
                                     'edit',
                                     'english_text',
                                     'greyscale',
                                     'hard_translated',
                                     'monochrome',
                                     'translated'],
                            'species': ['canid',
                                        'canine',
                                        'canis',
                                        'domestic_dog',
                                        'felid',
                                        'mammal',
                                        'pantherine',
                                        'tiger']},
                   'updated_at': '2021-01-30T12:13:17.061-05:00',
                   'uploader_id': 12705}},
 109793: {'changes': {'solo': True},
          'post': {'approver_id': None,
                   'change_seq': 31749156,
                   'comment_count': 0,
                   'created_at': '2011-01-01T00:29:43.297-05:00',
                   'description': '',
                   'duration': None,
                   'fav_count': 16,
                   'file': {'ext': 'jpg',
                            'height': 1020,
                            'md5': 'b7591e7934110dec747bf1e29598e1c7',
                            'size': 461941,
                            'url': 'https://static1.e621.net/data/b7/59/b7591e7934110dec747bf1e29598e1c7.jpg',
                            'width': 800},
                   'flags': {'deleted': False,
                             'flagged': False,
                             'note_locked': False,
                             'pending': False,
                             'rating_locked': False,
                             'status_locked': False},
                   'has_notes': False,
                   'id': 109793,
                   'is_favorited': False,
                   'locked_tags': [],
                   'pools': [603],
                   'preview': {'height': 150,
                               'url': 'https://static1.e621.net/data/preview/b7/59/b7591e7934110dec747bf1e29598e1c7.jpg',
                               'width': 117},
                   'rating': 's',
                   'relationships': {'children': [],
                                     'has_active_children': False,
                                     'has_children': False,
                                     'parent_id': None},
                   'sample': {'alternates': {},
                              'has': False,
                              'height': 1020,
                              'url': 'https://static1.e621.net/data/b7/59/b7591e7934110dec747bf1e29598e1c7.jpg',
                              'width': 800},
                   'score': {'down': 0, 'total': 3, 'up': 3},
                   'sources': ['Image board'],
                   'tags': {'artist': ['fruitz'],
                            'character': [],
                            'copyright': [],
                            'general': ['clock', 'male', 'text'],
                            'invalid': [],
                            'lore': [],
                            'meta': ['comic',
                                     'edit',
                                     'english_text',
                                     'greyscale',
                                     'hard_translated',
                                     'monochrome',
                                     'translated'],
                            'species': ['felid',
                                        'mammal',
                                        'pantherine',
                                        'tiger']},
                   'updated_at': '2021-01-30T12:13:07.051-05:00',
                   'uploader_id': 12705}},
 110559: {'changes': {'set:conman_test': True},
          'post': {'approver_id': 12705,
                   'change_seq': 31748272,
                   'comment_count': 8,
                   'created_at': '2011-01-05T13:30:35.115-05:00',
                   'description': '',
                   'duration': None,
                   'fav_count': 40,
                   'file': {'ext': 'jpg',
                            'height': 1188,
                            'md5': '836f51f28cbcaa62fc276cc7212eb640',
                            'size': 211604,
                            'url': 'https://static1.e621.net/data/83/6f/836f51f28cbcaa62fc276cc7212eb640.jpg',
                            'width': 891},
                   'flags': {'deleted': False,
                             'flagged': False,
                             'note_locked': False,
                             'pending': False,
                             'rating_locked': False,
                             'status_locked': False},
                   'has_notes': False,
                   'id': 110559,
                   'is_favorited': False,
                   'locked_tags': [],
                   'pools': [539],
                   'preview': {'height': 150,
                               'url': 'https://static1.e621.net/data/preview/83/6f/836f51f28cbcaa62fc276cc7212eb640.jpg',
                               'width': 112},
                   'rating': 's',
                   'relationships': {'children': [],
                                     'has_active_children': False,
                                     'has_children': False,
                                     'parent_id': None},
                   'sample': {'alternates': {},
                              'has': True,
                              'height': 1133,
                              'url': 'https://static1.e621.net/data/sample/83/6f/836f51f28cbcaa62fc276cc7212eb640.jpg',
                              'width': 850},
                   'score': {'down': -1, 'total': 15, 'up': 16},
                   'sources': ['https://www.furaffinity.net/view/4978289'],
                   'tags': {'artist': ['alectorfencer', 'rukis'],
                            'character': [],
                            'copyright': ['red_lantern'],
                            'general': ['4_toes',
                                        '5_fingers',
                                        'anthro',
                                        'barefoot',
                                        'biped',
                                        'candle',
                                        'claws',
                                        'clothed',
                                        'clothing',
                                        'collar',
                                        'dialogue',
                                        'digitigrade',
                                        'drawer',
                                        'ear_piercing',
                                        'ear_ring',
                                        'feet',
                                        'female',
                                        'fingers',
                                        'fur',
                                        'furniture',
                                        'inside',
                                        'lantern',
                                        'male',
                                        'metal_collar',
                                        'open_mouth',
                                        'piercing',
                                        'stool',
                                        'tan_body',
                                        'tan_fur',
                                        'teeth',
                                        'text',
                                        'toe_claws',
                                        'toes',
                                        'two_tone_tail',
                                        'walking'],
                            'invalid': [],
                            'lore': [],
                            'meta': ['3:4', 'comic', 'english_text'],
                            'species': ['canid',
                                        'canine',
                                        'canis',
                                        'domestic_dog',
                                        'hyaenid',
                                        'mammal',
                                        'spotted_hyena']},
                   'updated_at': '2021-06-02T03:02:32.451-04:00',
                   'uploader_id': 22949}},
 111092: {'changes': {'solo': True},
          'post': {'approver_id': 12705,
                   'change_seq': 31747505,
                   'comment_count': 0,
                   'created_at': '2011-01-08T18:18:15.252-05:00',
                   'description': '',
                   'duration': None,
                   'fav_count': 17,
                   'file': {'ext': 'jpg',
                            'height': 862,
                            'md5': '6d4ad66245d29447dbd2447239259489',
                            'size': 171673,
                            'url': 'https://static1.e621.net/data/6d/4a/6d4ad66245d29447dbd2447239259489.jpg',
                            'width': 600},
                   'flags': {'deleted': False,
                             'flagged': False,
                             'note_locked': False,
                             'pending': False,
                             'rating_locked': False,
                             'status_locked': False},
                   'has_notes': False,
                   'id': 111092,
                   'is_favorited': False,
                   'locked_tags': [],
                   'pools': [616],
                   'preview': {'height': 150,
                               'url': 'https://static1.e621.net/data/preview/6d/4a/6d4ad66245d29447dbd2447239259489.jpg',
                               'width': 104},
                   'rating': 's',
                   'relationships': {'children': [2377436],
                                     'has_active_children': False,
                                     'has_children': True,
                                     'parent_id': None},
                   'sample': {'alternates': {},
                              'has': False,
                              'height': 862,
                              'url': 'https://static1.e621.net/data/6d/4a/6d4ad66245d29447dbd2447239259489.jpg',
                              'width': 600},
                   'score': {'down': 0, 'total': 4, 'up': 4},
                   'sources': ['https://www.rainedog.com/'],
                   'tags': {'artist': ['dc_simpson'],
                            'character': [],
                            'copyright': ['rainedog'],
                            'general': ['anthro',
                                        'bodily_fluids',
                                        'doghouse',
                                        'female',
                                        'scared',
                                        'storm',
                                        'tears',
                                        'text',
                                        'thunder'],
                            'invalid': [],
                            'lore': [],
                            'meta': ['black_and_blue',
                                     'comic',
                                     'english_text',
                                     'url'],
                            'species': ['canid',
                                        'canine',
                                        'canis',
                                        'domestic_dog',
                                        'mammal']},
                   'updated_at': '2021-01-30T09:30:43.819-05:00',
                   'uploader_id': 4115}},
 111227: {'changes': {'group': True},
          'post': {'approver_id': 12705,
                   'change_seq': 25161118,
                   'comment_count': 11,
                   'created_at': '2011-01-09T15:51:30.084-05:00',
                   'description': '',
                   'duration': None,
                   'fav_count': 50,
                   'file': {'ext': 'jpg',
                            'height': 1510,
                            'md5': '9802bd5056062d5c87269240ebb7b2be',
                            'size': 298778,
                            'url': 'https://static1.e621.net/data/98/02/9802bd5056062d5c87269240ebb7b2be.jpg',
                            'width': 460},
                   'flags': {'deleted': False,
                             'flagged': False,
                             'note_locked': False,
                             'pending': False,
                             'rating_locked': False,
                             'status_locked': False},
                   'has_notes': False,
                   'id': 111227,
                   'is_favorited': False,
                   'locked_tags': [],
                   'pools': [],
                   'preview': {'height': 150,
                               'url': 'https://static1.e621.net/data/preview/98/02/9802bd5056062d5c87269240ebb7b2be.jpg',
                               'width': 45},
                   'rating': 's',
                   'relationships': {'children': [],
                                     'has_active_children': False,
                                     'has_children': False,
                                     'parent_id': None},
                   'sample': {'alternates': {},
                              'has': False,
                              'height': 1510,
                              'url': 'https://static1.e621.net/data/98/02/9802bd5056062d5c87269240ebb7b2be.jpg',
                              'width': 460},
                   'score': {'down': 0, 'total': 8, 'up': 8},
                   'sources': [],
                   'tags': {'artist': ['unknown_artist'],
                            'character': ['commander_shepard',
                                          'garrus_vakarian',
                                          "tali'zorah"],
                            'copyright': ['mass_effect'],
                            'general': ['<3',
                                        'dialogue',
                                        'female',
                                        'female/female',
                                        'hug',
                                        'text',
                                        'video_games'],
                            'invalid': [],
                            'lore': [],
                            'meta': ['comic',
                                     'english_text',
                                     'greyscale',
                                     'hi_res',
                                     'monochrome'],
                            'species': ['alien',
                                        'alien_humanoid',
                                        'arthropod',
                                        'bee',
                                        'human',
                                        'humanoid',
                                        'hymenopteran',
                                        'insect',
                                        'mammal',
                                        'quarian']},
                   'updated_at': '2021-02-18T23:50:51.637-05:00',
                   'uploader_id': 5340}},
 111592: {'changes': {'group': True},
          'post': {'approver_id': 12705,
                   'change_seq': 32230858,
                   'comment_count': 14,
                   'created_at': '2011-01-11T16:31:48.772-05:00',
                   'description': '',
                   'duration': None,
                   'fav_count': 45,
                   'file': {'ext': 'png',
                            'height': 1188,
                            'md5': '099c195067846cc1339cff1bd5496744',
                            'size': 1541811,
                            'url': 'https://static1.e621.net/data/09/9c/099c195067846cc1339cff1bd5496744.png',
                            'width': 891},
                   'flags': {'deleted': False,
                             'flagged': False,
                             'note_locked': False,
                             'pending': False,
                             'rating_locked': False,
                             'status_locked': False},
                   'has_notes': False,
                   'id': 111592,
                   'is_favorited': False,
                   'locked_tags': [],
                   'pools': [539],
                   'preview': {'height': 150,
                               'url': 'https://static1.e621.net/data/preview/09/9c/099c195067846cc1339cff1bd5496744.jpg',
                               'width': 112},
                   'rating': 'q',
                   'relationships': {'children': [],
                                     'has_active_children': False,
                                     'has_children': False,
                                     'parent_id': None},
                   'sample': {'alternates': {},
                              'has': True,
                              'height': 1133,
                              'url': 'https://static1.e621.net/data/sample/09/9c/099c195067846cc1339cff1bd5496744.jpg',
                              'width': 850},
                   'score': {'down': -2, 'total': 15, 'up': 17},
                   'sources': ['https://www.furaffinity.net/full/5054229/',
                               'https://www.furaffinity.net/view/5054229'],
                   'tags': {'artist': ['alectorfencer', 'rukis'],
                            'character': [],
                            'copyright': ['red_lantern'],
                            'general': ['5_fingers',
                                        'anthro',
                                        'barefoot',
                                        'biped',
                                        'claws',
                                        'clothed',
                                        'clothing',
                                        'collar',
                                        'dialogue',
                                        'ear_piercing',
                                        'ear_ring',
                                        'eyes_closed',
                                        'feet',
                                        'female',
                                        'finger_claws',
                                        'fingerless_gloves',
                                        'fingers',
                                        'fur',
                                        'gloves',
                                        'glowing',
                                        'grey_body',
                                        'grey_fur',
                                        'handwear',
                                        'holding_object',
                                        'inside',
                                        'male',
                                        'metal_collar',
                                        'mouth_hold',
                                        'open_mouth',
                                        'piercing',
                                        'slave',
                                        'spots',
                                        'spotted_body',
                                        'spotted_fur',
                                        'standing',
                                        'teeth',
                                        'text',
                                        'whiskers'],
                            'invalid': [],
                            'lore': [],
                            'meta': ['3:4', 'comic', 'english_text'],
                            'species': ['brown_hyena',
                                        'felid',
                                        'hyaenid',
                                        'mammal',
                                        'pantherine',
                                        'spotted_hyena',
                                        'tiger']},
                   'updated_at': '2021-06-02T03:02:32.555-04:00',
                   'uploader_id': 22949}},
 111765: {'changes': {'set:conman_test': True},
          'post': {'approver_id': 12705,
                   'change_seq': 31746904,
                   'comment_count': 0,
                   'created_at': '2011-01-13T00:14:48.103-05:00',
                   'description': '',
                   'duration': None,
                   'fav_count': 6,
                   'file': {'ext': 'jpg',
                            'height': 1500,
                            'md5': '0d1e1015d984dce471eba95c8e009c07',
                            'size': 397232,
                            'url': 'https://static1.e621.net/data/0d/1e/0d1e1015d984dce471eba95c8e009c07.jpg',
                            'width': 1050},
                   'flags': {'deleted': False,
                             'flagged': False,
                             'note_locked': False,
                             'pending': False,
                             'rating_locked': False,
                             'status_locked': False},
                   'has_notes': False,
                   'id': 111765,
                   'is_favorited': False,
                   'locked_tags': [],
                   'pools': [620],
                   'preview': {'height': 150,
                               'url': 'https://static1.e621.net/data/preview/0d/1e/0d1e1015d984dce471eba95c8e009c07.jpg',
                               'width': 105},
                   'rating': 'q',
                   'relationships': {'children': [],
                                     'has_active_children': False,
                                     'has_children': False,
                                     'parent_id': None},
                   'sample': {'alternates': {},
                              'has': True,
                              'height': 1214,
                              'url': 'https://static1.e621.net/data/sample/0d/1e/0d1e1015d984dce471eba95c8e009c07.jpg',
                              'width': 850},
                   'score': {'down': 0, 'total': 1, 'up': 1},
                   'sources': [],
                   'tags': {'artist': ['unagimaru'],
                            'character': ['eruru', 'hakuoro'],
                            'copyright': ['utawarerumono'],
                            'general': ['breasts', 'female', 'male', 'text'],
                            'invalid': [],
                            'lore': [],
                            'meta': ['comic',
                                     'english_text',
                                     'greyscale',
                                     'hi_res',
                                     'monochrome'],
                            'species': ['animal_humanoid',
                                        'canid',
                                        'canid_humanoid',
                                        'canine',
                                        'canine_humanoid',
                                        'canis',
                                        'dog_humanoid',
                                        'domestic_dog',
                                        'humanoid',
                                        'mammal',
                                        'mammal_humanoid']},
                   'updated_at': '2021-01-30T08:17:55.214-05:00',
                   'uploader_id': 17464}},
 111888: {'changes': {'set:conman_test': True},
          'post': {'approver_id': 2080,
                   'change_seq': 19393485,
                   'comment_count': 0,
                   'created_at': '2011-01-13T18:09:34.804-05:00',
                   'description': '',
                   'duration': None,
                   'fav_count': 1,
                   'file': {'ext': 'jpg',
                            'height': 1080,
                            'md5': 'b5bd36901aa3948f71334a27d6a38eb2',
                            'size': 83290,
                            'url': 'https://static1.e621.net/data/b5/bd/b5bd36901aa3948f71334a27d6a38eb2.jpg',
                            'width': 380},
                   'flags': {'deleted': False,
                             'flagged': False,
                             'note_locked': False,
                             'pending': False,
                             'rating_locked': False,
                             'status_locked': False},
                   'has_notes': False,
                   'id': 111888,
                   'is_favorited': False,
                   'locked_tags': [],
                   'pools': [],
                   'preview': {'height': 150,
                               'url': 'https://static1.e621.net/data/preview/b5/bd/b5bd36901aa3948f71334a27d6a38eb2.jpg',
                               'width': 52},
                   'rating': 's',
                   'relationships': {'children': [],
                                     'has_active_children': False,
                                     'has_children': False,
                                     'parent_id': None},
                   'sample': {'alternates': {},
                              'has': False,
                              'height': 1080,
                              'url': 'https://static1.e621.net/data/b5/bd/b5bd36901aa3948f71334a27d6a38eb2.jpg',
                              'width': 380},
                   'score': {'down': 0, 'total': 0, 'up': 0},
                   'sources': [],
                   'tags': {'artist': ['unknown_artist'],
                            'character': ['holo'],
                            'copyright': ['spice_and_wolf'],
                            'general': ['female', 'male', 'text'],
                            'invalid': [],
                            'lore': [],
                            'meta': ['4koma',
                                     'comic',
                                     'greyscale',
                                     'japanese_text',
                                     'monochrome',
                                     'translation_request'],
                            'species': ['animal_humanoid',
                                        'canid',
                                        'canid_humanoid',
                                        'canine',
                                        'canine_humanoid',
                                        'canis',
                                        'humanoid',
                                        'mammal',
                                        'mammal_humanoid',
                                        'wolf',
                                        'wolf_humanoid']},
                   'updated_at': '2020-06-23T22:30:16.421-04:00',
                   'uploader_id': 17464}},
 112125: {'changes': {'solo': True},
          'post': {'approver_id': 12705,
                   'change_seq': 33890682,
                   'comment_count': 1,
                   'created_at': '2011-01-20T00:53:12.421-05:00',
                   'description': '',
                   'duration': None,
                   'fav_count': 70,
                   'file': {'ext': 'jpg',
                            'height': 800,
                            'md5': '909a2b8d651f1800456bdbaced47d008',
                            'size': 79078,
                            'url': 'https://static1.e621.net/data/90/9a/909a2b8d651f1800456bdbaced47d008.jpg',
                            'width': 594},
                   'flags': {'deleted': False,
                             'flagged': False,
                             'note_locked': False,
                             'pending': False,
                             'rating_locked': True,
                             'status_locked': False},
                   'has_notes': False,
                   'id': 112125,
                   'is_favorited': False,
                   'locked_tags': [],
                   'pools': [11186],
                   'preview': {'height': 150,
                               'url': 'https://static1.e621.net/data/preview/90/9a/909a2b8d651f1800456bdbaced47d008.jpg',
                               'width': 111},
                   'rating': 'e',
                   'relationships': {'children': [],
                                     'has_active_children': False,
                                     'has_children': False,
                                     'parent_id': None},
                   'sample': {'alternates': {},
                              'has': False,
                              'height': 800,
                              'url': 'https://static1.e621.net/data/90/9a/909a2b8d651f1800456bdbaced47d008.jpg',
                              'width': 594},
                   'score': {'down': -3, 'total': 14, 'up': 17},
                   'sources': ['https://www.furaffinity.net/view/3534862/',
                               'https://www.furaffinity.net/user/brokenwing/'],
                   'tags': {'artist': ['freckles_(artist)'],
                            'character': ['bowser', 'brokenwing'],
                            'copyright': ['mario_bros', 'nintendo'],
                            'general': ['2_horns',
                                        'anthro',
                                        'areola',
                                        'auto_penis_lick',
                                        'autofellatio',
                                        'back_horn',
                                        'balls',
                                        'belly',
                                        'big_breasts',
                                        'big_penis',
                                        'biped',
                                        'black_pupils',
                                        'blue_eyes',
                                        'bodily_fluids',
                                        'body_outline',
                                        'breasts',
                                        'countershade_torso',
                                        'countershading',
                                        'cum',
                                        'dark_pupils',
                                        'ear_fins',
                                        'ear_frill',
                                        'erection',
                                        'fin',
                                        'fin_frill',
                                        'foreskin',
                                        'foreskin_play',
                                        'frill_(anatomy)',
                                        'genital_fluids',
                                        'genitals',
                                        'green_body',
                                        'green_ear_fins',
                                        'green_face',
                                        'green_fin',
                                        'green_scales',
                                        'green_tail',
                                        'green_wings',
                                        'gynomorph',
                                        'hand_on_penis',
                                        'head_horn',
                                        'holding_penis',
                                        'horn',
                                        'huge_penis',
                                        'humanoid_genitalia',
                                        'humanoid_penis',
                                        'hyper',
                                        'hyper_genitalia',
                                        'hyper_penis',
                                        'imprint',
                                        'intersex',
                                        'iris',
                                        'licking',
                                        'light_balls',
                                        'light_belly',
                                        'light_breasts',
                                        'light_horn',
                                        'light_penis',
                                        'masturbation',
                                        'membrane_(anatomy)',
                                        'membranous_frill',
                                        'monotone_balls',
                                        'monotone_belly',
                                        'monotone_breasts',
                                        'monotone_genitals',
                                        'monotone_penis',
                                        'multicolored_face',
                                        'multicolored_tail',
                                        'multicolored_wings',
                                        'nipples',
                                        'non-mammal_breasts',
                                        'nude',
                                        'oral',
                                        'oral_masturbation',
                                        'penile',
                                        'penile_masturbation',
                                        'penis',
                                        'pink_areola',
                                        'pink_nipples',
                                        'pink_tongue',
                                        'pupils',
                                        'purple_background',
                                        'scales',
                                        'self_lick',
                                        'simple_background',
                                        'small_pupils',
                                        'soft_vore',
                                        'solo_focus',
                                        'tongue',
                                        'tongue_in_foreskin',
                                        'tongue_out',
                                        'two_tone_face',
                                        'two_tone_tail',
                                        'two_tone_wings',
                                        'uncut',
                                        'video_games',
                                        'vore',
                                        'white_horn',
                                        'wings',
                                        'yellow_balls',
                                        'yellow_belly',
                                        'yellow_body',
                                        'yellow_breasts',
                                        'yellow_countershading',
                                        'yellow_ear_frill',
                                        'yellow_face',
                                        'yellow_frill',
                                        'yellow_membrane',
                                        'yellow_penis',
                                        'yellow_scales',
                                        'yellow_tail',
                                        'yellow_wings'],
                            'invalid': [],
                            'lore': [],
                            'meta': ['2010', 'digital_media_(artwork)'],
                            'species': ['dragon', 'scalie']},
                   'updated_at': '2021-07-08T16:04:02.771-04:00',
                   'uploader_id': 18867}},
 112671: {'changes': {'set:conman_test': True},
          'post': {'approver_id': 2080,
                   'change_seq': 31746114,
                   'comment_count': 16,
                   'created_at': '2011-01-22T14:07:29.785-05:00',
                   'description': '',
                   'duration': None,
                   'fav_count': 117,
                   'file': {'ext': 'png',
                            'height': 358,
                            'md5': 'cdd441f3493ac57df26c9a453bf9a3d6',
                            'size': 162170,
                            'url': 'https://static1.e621.net/data/cd/d4/cdd441f3493ac57df26c9a453bf9a3d6.png',
                            'width': 913},
                   'flags': {'deleted': False,
                             'flagged': False,
                             'note_locked': False,
                             'pending': False,
                             'rating_locked': False,
                             'status_locked': False},
                   'has_notes': False,
                   'id': 112671,
                   'is_favorited': False,
                   'locked_tags': ['conditional_dnp'],
                   'pools': [2653],
                   'preview': {'height': 58,
                               'url': 'https://static1.e621.net/data/preview/cd/d4/cdd441f3493ac57df26c9a453bf9a3d6.jpg',
                               'width': 150},
                   'rating': 'q',
                   'relationships': {'children': [],
                                     'has_active_children': False,
                                     'has_children': False,
                                     'parent_id': None},
                   'sample': {'alternates': {},
                              'has': True,
                              'height': 333,
                              'url': 'https://static1.e621.net/data/sample/cd/d4/cdd441f3493ac57df26c9a453bf9a3d6.jpg',
                              'width': 850},
                   'score': {'down': -3, 'total': 42, 'up': 45},
                   'sources': [],
                   'tags': {'artist': ['conditional_dnp',
                                       'jay_naylor',
                                       'rick_griffin'],
                            'character': ['fisk_black',
                                          'grape_jelly_(housepets!)',
                                          'lucy_black',
                                          'peanut_butter_(housepets!)',
                                          'webcomic_character'],
                            'copyright': ['housepets!'],
                            'general': ['anthro',
                                        'female',
                                        'flat_chested',
                                        'humor',
                                        'male',
                                        'male/female',
                                        'pillow',
                                        'sibling',
                                        'text',
                                        'twincest',
                                        'twins',
                                        'webcomic'],
                            'invalid': [],
                            'lore': ['incest_(lore)'],
                            'meta': ['comic',
                                     'edit',
                                     'english_text',
                                     'monochrome'],
                            'species': ['canid',
                                        'canine',
                                        'canis',
                                        'domestic_cat',
                                        'domestic_dog',
                                        'felid',
                                        'feline',
                                        'felis',
                                        'mammal']},
                   'updated_at': '2021-07-06T00:10:35.614-04:00',
                   'uploader_id': 23670}},
 112709: {'changes': {'set:conman_test': True},
          'post': {'approver_id': 2080,
                   'change_seq': 31746086,
                   'comment_count': 8,
                   'created_at': '2011-01-22T20:10:32.325-05:00',
                   'description': '',
                   'duration': None,
                   'fav_count': 36,
                   'file': {'ext': 'jpg',
                            'height': 1674,
                            'md5': 'e1d2e6b218b5746188f633b5a9425a68',
                            'size': 434011,
                            'url': 'https://static1.e621.net/data/e1/d2/e1d2e6b218b5746188f633b5a9425a68.jpg',
                            'width': 780},
                   'flags': {'deleted': False,
                             'flagged': False,
                             'note_locked': False,
                             'pending': False,
                             'rating_locked': False,
                             'status_locked': False},
                   'has_notes': False,
                   'id': 112709,
                   'is_favorited': False,
                   'locked_tags': [],
                   'pools': [],
                   'preview': {'height': 150,
                               'url': 'https://static1.e621.net/data/preview/e1/d2/e1d2e6b218b5746188f633b5a9425a68.jpg',
                               'width': 69},
                   'rating': 'q',
                   'relationships': {'children': [],
                                     'has_active_children': False,
                                     'has_children': False,
                                     'parent_id': None},
                   'sample': {'alternates': {},
                              'has': False,
                              'height': 1674,
                              'url': 'https://static1.e621.net/data/e1/d2/e1d2e6b218b5746188f633b5a9425a68.jpg',
                              'width': 780},
                   'score': {'down': 0, 'total': 8, 'up': 8},
                   'sources': [],
                   'tags': {'artist': ['annie-mae'],
                            'character': ['patrick_star',
                                          'sandy_cheeks',
                                          'spongebob_squarepants_(character)'],
                            'copyright': ['nickelodeon',
                                          'spongebob_squarepants'],
                            'general': ['!',
                                        '?',
                                        'anthro',
                                        'breast_grab',
                                        'breasts',
                                        'female',
                                        'half-closed_eyes',
                                        'hand_on_breast',
                                        'humor',
                                        'male',
                                        'moon',
                                        'narrowed_eyes',
                                        'pain',
                                        'punch',
                                        'text'],
                            'invalid': [],
                            'lore': [],
                            'meta': ['2005',
                                     'comic',
                                     'english_text',
                                     'greyscale',
                                     'hi_res',
                                     'monochrome'],
                            'species': ['asterozoan',
                                        'echinoderm',
                                        'mammal',
                                        'marine',
                                        'rodent',
                                        'sciurid',
                                        'sea_sponge',
                                        'starfish',
                                        'tree_squirrel']},
                   'updated_at': '2021-01-30T06:51:07.325-05:00',
                   'uploader_id': 16396}}
}

